SendMode Input

q::Send, ni return
w::Send, to return
e::Send, ka return
r::Send, ha return
t::Send, chi return
y::Send, gu return
u::Send, ko return
i::Send, i return
o::Send, shi return
p::Send, ba return
=::Send, hi return
a::Send, no return
f::Send, nn return
g::Send, txu return
x::Send, ma return
c::Send, ki return
v::Send, ru return
b::Send, tsu return
n::Send, te return
::kq::Send, xo return
::kw::Send, go return
::ke::Send, hu return
::kr::Send, ge return
::kt::Send, xa return
::ka::Send, ho return
::ks::Send, zi return
::kd::Send, re return
::kf::Send, mo return
::kz::Send, du return
::kx::Send, zo return
::kc::Send, bo return
::kv::Send, mu return
::kb::Send, xyu return
::dy::Send, xyo return
::du::Send, pa return
::di::Send, yo return
::do::Send, mi return
::dp::Send, xu return
::dj::Send, a return
::dk::Send, re return
::dl::Send, o return
::d;::Send, e return
::dn::Send, se return
::dm::Send, ne return
::d,::Send, be return
::d.::Send, bu return
::d/::Send, vu return
::lq::Send, xi return
::lw::Send, me return
::le::Send, ke return
::lr::Send, xya return
::lt::Send, di return
::la::Send, wo return
::ls::Send, sa return
::ld::Send, o return
::lf::Send, ri return
::lx::Send, za return
::lc::Send, gi return
::lv::Send, ro return
::lb::Send, bu return
::su::Send, pe return
::si::Send, do return
::so::Send, ya return
::sp::Send, xe return
::sk::Send, zi return
::sl::Send, sa return
::s;::Send, so return
::sn::Send, wa return
Q::Send, myo return
W::Send, gyo return
E::Send, tyu return
R::Send, fo return
T::Send, the return
Y::Send, rya return
U::Send, je return
I::Send, kyu return
O::Send, hyo return
P::Send, bya return
!::Send, nya return
?::Send, pyu return
A::Send, tyo return
S::Send, sya return
D::Send, jo return
F::Send, syu return
G::Send, kya return
H::Send, myu return
J::Send, syo return
K::Send, kyo return
L::Send, ryo return
&::Send, ju return
Z::Send, fa return
X::Send, byo return
C::Send, thi return
V::Send, nyu return
B::Send, fi return
N::Send, gya return
::ssb::Send, sye return
::SSA::Send, nyo return
::SSB::Send, whe return
::SSC::Send, pyo return
