q::Send {Text}ni ; に
w::Send {Text}to ; と
e::Send {Text}ka ; か
r::Send {Text}ha ; は
t::Send {Text}chi ; ち
y::Send {Text}gu ; ぐ
u::Send {Text}ko ; こ
i::Send {Text}i ; い
o::Send {Text}shi ; し
p::Send {Text}ba ; ば
=::Send {Text}hi ; ひ
a::Send {Text}no ; の
f::Send {Text}nn ; ん
g::Send {Text}txu ; っ
h::Send {Text}ku ; く
j::Send {Text}j ; う
`;::Send {Text}na ; な
`:::Send {Text} ; ー
z::Send {Text}su ; す
x::Send {Text}ma ; ま
c::Send {Text}ki ; き
v::Send {Text}ru ; る
b::Send {Text}tsu ; つ
n::Send {Text}te ; て
m::Send {Text}ta ; た
,::Send {Text}de ; で
.::Send {Text}ga ; が
/::Send {Text}bu ; ぶ
